package com.jhu.socialnetworking.database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.sql.DataSource;

/**
 * Performs the initialization of the database once for the application using singleton pattern
 * @author chris
 *
 */
public class InitializeDatabase {

	/**
	 * The datasource used to perist JERCs data
	 */
	private DataSource dataSource;
	
	/**
	 * The single instance of the database initializer using the singleton pattern
	 */
	private static InitializeDatabase instance = null;
	
	/**
	 * True if the database is initialized
	 */
	private boolean isDatabaseInitialized = false;

	/**
	 * Get the single instance of the database initializer
	 */
	public static InitializeDatabase getInstance() {
		if (instance == null) {
			instance = new InitializeDatabase();
		}
		return instance;
	}

	protected InitializeDatabase() {
		// Exists only to defeat instantiation.
	}

	/**
	 * Initializes the database and each of its tables once
	 * @param dataSource the datasource used to perist JERCs data
	 */
	public void initializeDatabase(DataSource dataSource) {

		// if the database is initialized, don't initialize it again
		if (!isDatabaseInitialized) {
			
			// set the database based on the datasource provided by the caller
			this.dataSource = dataSource;
			
			// configure the student table
			initializeStudentTable();
			
			// configure the course table
			initializeCourseTable();
			
			// configure the professor table
			initializeProfessorTable();
			
			// configure the evaluation table
			initializeEvaluationTable();
			
			// configure the registration table
			initializeRegistrationTable();
			
			// the database is initalized; don't initialize it again
			isDatabaseInitialized = true;
		}
	}

	/**
	 * Creates the REGISTRATION table to persist evaluation data
	 */
	public void initializeRegistrationTable() {
		
		String sql = null;
		Connection conn = null;
		PreparedStatement ps = null;

		try {

			// create a REGISTRATION table with a evaluation_id as the primary key
			sql = "CREATE TABLE Registration ("
					+ "registration_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
					+ "student_id int, course_id varchar(200), professor_id int, semester varchar(1000), year int, PRIMARY KEY (registration_id));";
			conn = dataSource.getConnection();
			ps = conn.prepareStatement(sql);
			ps.execute();

		} catch (SQLException e) {
			System.out.println(e.getMessage());
		}
		
	}
	
	/**
	 * Creates the EVALUATION table to persist evaluation data
	 */
	public void initializeEvaluationTable() {
		
		String sql = null;
		Connection conn = null;
		PreparedStatement ps = null;

		try {

			// create a EVALUATION table with a evaluation_id as the primary key
			sql = "CREATE TABLE Evaluation ("
					+ "evaluation_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
					+ "registration_id int, rating varchar(1000), comments varchar(1000), PRIMARY KEY (evaluation_id));";
			conn = dataSource.getConnection();
			ps = conn.prepareStatement(sql);
			ps.execute();

		} catch (SQLException e) {
			System.out.println(e.getMessage());
		}

	}
	
	/**
	 * Creates the COURSE table to persist course data
	 */
	public void initializeCourseTable() {
		
		String sql = null;
		Connection conn = null;
		PreparedStatement ps = null;

		try {

			// create a COURSE table with a course_id as the primary key
			sql = "CREATE TABLE Course ("
					+ "course_id varchar(200), "
					+ "course_name varchar(200), course_description varchar(1000), PRIMARY KEY (course_id));";
			conn = dataSource.getConnection();
			ps = conn.prepareStatement(sql);
			ps.execute();

		} catch (SQLException e) {
			System.out.println(e.getMessage());
		}

	}
	
	/**
	 * Creates the STUDENT table to persist student data
	 */
	public void initializeStudentTable() {

		String sql = null;
		Connection conn = null;
		PreparedStatement ps = null;

		try {

			// create a STUDENT table with a student_id as the primary key
			// include a first name and last name for each student
			sql = "CREATE TABLE Student ("
					+ "student_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
					+ "first_name varchar(200), last_name varchar(200), PRIMARY KEY (student_id));";
			conn = dataSource.getConnection();
			ps = conn.prepareStatement(sql);
			ps.execute();

		} catch (SQLException e) {
			System.out.println(e.getMessage());
		}

	}
	
	/**
	 * Creates the PROFESSOR table to persist student data
	 */
	public void initializeProfessorTable() {

		String sql = null;
		Connection conn = null;
		PreparedStatement ps = null;

		try {

			// create a PROFESSOR table with a professor_id as the primary key
			// include a first name and last name for each professor
			sql = "CREATE TABLE Professor ("
					+ "professor_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
					+ "first_name varchar(200), last_name varchar(200), PRIMARY KEY (professor_id));";
			conn = dataSource.getConnection();
			ps = conn.prepareStatement(sql);
			ps.execute();

		} catch (SQLException e) {
			System.out.println(e.getMessage());
		}

	}
}
