package com.jhu.socialnetworking.database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.sql.DataSource;

/**
 * Performs the initialization of the database once for the application using singleton pattern
 * @author chris
 *
 */
public class InitializeDatabase {

	/**
	 * The datasource used to perist JERCs data
	 */
	private DataSource dataSource;
	
	/**
	 * The single instance of the database initializer using the singleton pattern
	 */
	private static InitializeDatabase instance = null;
	
	/**
	 * True if the database is initialized
	 */
	private boolean isDatabaseInitialized = false;

	/**
	 * Get the single instance of the database initializer
	 */
	public static InitializeDatabase getInstance() {
		if (instance == null) {
			instance = new InitializeDatabase();
		}
		return instance;
	}

	protected InitializeDatabase() {
		// Exists only to defeat instantiation.
	}

	/**
	 * Initializes the database and each of its tables once
	 * @param dataSource the datasource used to perist JERCs data
	 */
	public void initializeDatabase(DataSource dataSource) {

		// if the database is initialized, don't initialize it again
		if (!isDatabaseInitialized) {
			
			// set the database based on the datasource provided by the caller
			this.dataSource = dataSource;
			
			// configure the student table
			initializeStudentTable();
			
			// the database is initalized; don't initialize it again
			isDatabaseInitialized = true;
		}
	}

	/**
	 * Creates the STUDENT table to persist student data
	 */
	public void initializeStudentTable() {

		String sql = null;
		Connection conn = null;
		PreparedStatement ps = null;

		try {

			// create a STUDENT table with a student_id as the primary key
			// include a first name and last name for each student
			sql = "CREATE TABLE Student ("
					+ "student_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, "
					+ "name varchar(10), "
					+ "email varchar(10), "
					+ "PRIMARY KEY (student_id));";
			conn = dataSource.getConnection();
			ps = conn.prepareStatement(sql);
			ps.execute();

		} catch (SQLException e) {
			System.out.println(e.getMessage());
		}

	}
}
